import admin from "firebase-admin";import {readFileSync,writeFileSync} from "node:fs";
admin.initializeApp({credential:admin.credential.cert(JSON.parse(readFileSync("./firebase-service-account.json","utf8")))});
const db=admin.firestore();
const s=await db.collection("workspaces/team/accounts/ziad-cash/tx").get();
const all=s.docs.map(d=>({id:d.id,...d.data()}));
const xl=all.filter(t=>t.src==="excel"), od=all.filter(t=>t.src==="odoo"), wa=all.filter(t=>t.src==="whatsapp");
const mv=t=>((t.credit||0)-(t.debit||0));
const sum=a=>+(a.reduce((x,t)=>x+mv(t),0)).toFixed(2);
console.log("excel rows",xl.length,"net",sum(xl));
console.log("odoo lines",od.length,"| tied",od.filter(t=>t.dupOf).length,"| odooOnly",od.filter(t=>t.odooOnly).length,"net of odooOnly",sum(od.filter(t=>t.odooOnly)));
console.log("whatsapp",wa.length,"| counted",wa.filter(t=>!t.excluded).length,"net",sum(wa.filter(t=>!t.excluded)));
const only=od.filter(t=>t.odooOnly).sort((a,b)=>Math.abs(mv(b))-Math.abs(mv(a)));
console.log("\ntop 20 Odoo lines that are NOT in his sheet:");
only.slice(0,20).forEach(t=>console.log(`  ${t.date} ${String(mv(t)).padStart(10)} ${t.ref||""} | ${(t.description||"").slice(0,60)} | ${t.company||""}`));
const byYear={};only.forEach(t=>{const y=(t.date||"").slice(0,4);byYear[y]=(byYear[y]||0)+mv(t);});
console.log("odooOnly by year:",JSON.stringify(Object.fromEntries(Object.entries(byYear).map(([k,v])=>[k,+v.toFixed(2)]))));
writeFileSync("D:/vscode/odoo/out/ziad-odoo-only.json",JSON.stringify(only.map(t=>({date:t.date,amount:mv(t),ref:t.ref,desc:t.description,company:t.company})),null,1));
const unl=xl.filter(t=>!t.matchedOdoo&&!t.bookedMove&&!t.noBook);
console.log("\nsheet rows with nothing in Odoo:",unl.length,"net",sum(unl));
process.exit(0);
